"""`techdaily run` produces today's episode end to end; every step resumes if a previous run stopped."""

from __future__ import annotations

import argparse
import json
import logging
import os
import shutil
import subprocess
import sys
from datetime import date
from logging.handlers import RotatingFileHandler
from pathlib import Path

from .config import Config, load_config
from .episode import STEPS, Episode, episode_for

log = logging.getLogger("techdaily")


def setup_logging(cfg: Config) -> None:
    logs = cfg.root / "logs"
    logs.mkdir(exist_ok=True)
    root = logging.getLogger()
    root.setLevel(logging.INFO)
    fmt = logging.Formatter("%(asctime)s %(levelname)s %(name)s: %(message)s")
    fh = RotatingFileHandler(logs / "techdaily.log", maxBytes=2_000_000, backupCount=5, encoding="utf-8")
    fh.setFormatter(fmt)
    root.addHandler(fh)
    if sys.stderr is not None:
        sh = logging.StreamHandler()
        sh.setFormatter(fmt)
        root.addHandler(sh)
    logging.getLogger("httpx").setLevel(logging.WARNING)


def notify(cfg: Config, subject: str, message: str) -> None:
    target = (cfg.raw.get("notify") or {}).get("hermes_target")
    hermes = shutil.which("hermes")
    if not target or not hermes:
        return
    try:
        subprocess.run([hermes, "send", "--to", str(target), "--subject", subject, "--quiet"], input=message,
                       text=True, encoding="utf-8", timeout=60, capture_output=True)
    except Exception as exc:  # noqa: BLE001
        log.warning("notify failed: %s", exc)


class Lock:
    def __init__(self, path: Path):
        self.path = path
        self.fh = None

    def __enter__(self):
        self.fh = open(self.path, "a+")
        if os.name == "nt":
            import msvcrt

            try:
                msvcrt.locking(self.fh.fileno(), msvcrt.LK_NBLCK, 1)
            except OSError as exc:
                self.fh.close()
                raise SystemExit("another techdaily run is in progress") from exc
        else:
            import fcntl

            try:
                fcntl.flock(self.fh.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
            except OSError as exc:
                self.fh.close()
                raise SystemExit("another techdaily run is in progress") from exc
        return self

    def __exit__(self, *exc):
        self.fh.close()


def run_steps(cfg: Config, ep: Episode, until: str) -> None:
    for step in STEPS[: STEPS.index(until) + 1]:
        if ep.done(step):
            continue
        log.info("episode %s: %s", ep.dir.name, step)
        getattr(ep, f"step_{step}")()


def cmd_run(cfg: Config, args) -> int:
    from .daily import FORMATS, run_day

    day = date.fromisoformat(args.date) if args.date else None
    only = tuple(args.only.split(",")) if args.only else FORMATS
    with Lock(cfg.root / ".techdaily.lock"):
        try:
            results = run_day(cfg, day, only=only, hold=True if args.hold else None)
        except Exception as exc:  # noqa: BLE001
            log.exception("daily run failed")
            notify(cfg, "Daily videos failed", f"{exc}\nResume with: techdaily run")
            return 1
    lines = [f"{fmt}: {r['title']} (job {r['job']}{', held for approval' if r['held'] else ''})"
             for fmt, r in results.items()]
    notify(cfg, "Daily videos ready", "\n".join(lines))
    print("\n".join(lines))
    return 0


def cmd_status(cfg: Config, args) -> int:
    for folder in sorted(cfg.episodes_dir.glob("*"))[-args.last:]:
        ep = Episode(cfg, folder)
        state = ep.state
        last = next((s for s in reversed(STEPS) if s in state), "-")
        tool = state.get("pick", {}).get("tool", "?")
        extra = state.get("queue", {}).get("ytauto_job", "")
        print(f"{folder.name}  {last:<9} {tool:<28} {extra}")
    return 0


def cmd_redo(cfg: Config, args) -> int:
    """Forget a step (and everything after it) so the next run repeats it."""
    ep = episode_for(cfg, date.fromisoformat(args.date) if args.date else None)
    state = ep.state
    for step in STEPS[STEPS.index(args.step):]:
        state.pop(step, None)
    ep.state_path.write_text(json.dumps(state, indent=2), encoding="utf-8")
    print(f"{ep.dir.name}: will redo from {args.step}")
    return 0


SHIM = '''"""Generated by `techdaily integrate`. Hermes cron runs this daily in --no-agent mode.

Starts `techdaily run` in the background and returns at once (a build takes an hour or more).
techdaily sends its own notifications; empty stdout keeps Hermes silent.
"""
import subprocess
import sys

PYTHON = {python!r}
PROJECT = {project!r}

flags = subprocess.DETACHED_PROCESS | subprocess.CREATE_NEW_PROCESS_GROUP if sys.platform == "win32" else 0
kwargs = dict(cwd=PROJECT, stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
              close_fds=True)
try:
    subprocess.Popen([PYTHON, "-m", "techdaily", "run"], creationflags=flags | 0x01000000, **kwargs)
except OSError:
    subprocess.Popen([PYTHON, "-m", "techdaily", "run"], creationflags=flags, **kwargs)
'''


def cmd_integrate(cfg: Config, args) -> int:
    home = Path(os.environ.get("HERMES_HOME") or (Path(os.environ["LOCALAPPDATA"]) / "hermes"
                                                  if os.name == "nt" else Path.home() / ".hermes"))
    scripts = home / "scripts"
    scripts.mkdir(parents=True, exist_ok=True)
    pyw = Path(sys.executable).with_name("pythonw.exe")
    (scripts / "techdaily_run.py").write_text(
        SHIM.format(python=str(pyw if pyw.exists() else sys.executable), project=str(cfg.root)), encoding="utf-8")
    hermes = shutil.which("hermes")
    if not hermes:
        print("hermes not on PATH")
        return 1
    listing = subprocess.run([hermes, "cron", "list"], capture_output=True, text=True, encoding="utf-8").stdout
    if "techdaily-run" in listing:
        print("hermes cron job 'techdaily-run' already exists")
        return 0
    res = subprocess.run([hermes, "cron", "create", args.cron, "--no-agent", "--script", "techdaily_run.py",
                          "--name", "techdaily-run", "--deliver", "local"], capture_output=True, text=True,
                         encoding="utf-8")
    print(res.stdout.strip() or res.stderr.strip())
    return res.returncode


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="techdaily", description="Daily tech-tool explainer producer")
    ap.add_argument("--config")
    sub = ap.add_subparsers(dest="cmd", required=True)
    r = sub.add_parser("run", help="produce (or resume) today's episode")
    r.add_argument("--date", help="episode date YYYY-MM-DD (default today)")
    r.add_argument("--only", help="comma-separated formats to make: short,main (default both)")
    r.add_argument("--hold", action="store_true", help="queue the videos held for approval")
    r.set_defaults(fn=cmd_run)
    s = sub.add_parser("status", help="list recent episodes")
    s.add_argument("--last", type=int, default=10)
    s.set_defaults(fn=cmd_status)
    d = sub.add_parser("redo", help="repeat a step and everything after it")
    d.add_argument("step", choices=STEPS)
    d.add_argument("--date")
    d.set_defaults(fn=cmd_redo)
    i = sub.add_parser("integrate", help="register the daily run with Hermes cron")
    i.add_argument("--cron", default="0 9 * * *", help="cron schedule in local time (default 09:00 daily)")
    i.set_defaults(fn=cmd_integrate)
    args = ap.parse_args(argv)
    cfg = load_config(args.config)
    setup_logging(cfg)
    return args.fn(cfg, args)
